name: otaqu
description: Created by Dani Rycki Dinata
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  json_serializable: ^6.5.4
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sqflite: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: assets/images/logo.png
  android: true
  ios: true

flutter:

  uses-material-design: true
  assets:
    - assets/fonts/.
    - assets/images/.
